name: 'Thank You Action'
description: 'Saying thanks, pardner'
author: 'Tiggles'

inputs: 
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
runs: 
  using: 'node16'
  main: 'src/index.js'